"use client";
import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import cls from "classnames";
import { Nav, Container, Navbar } from "react-bootstrap";
import { usePathname } from "next/navigation";
// export const metadata = {
//   title: "Attendance management system",
//   description: "Generated by create next app",
// };
import "bootstrap/dist/css/bootstrap.min.css";
export default function RootLayout({ children }) {
  const path = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        {path !== "/login" && (
          <Navbar bg="dark" variant="dark" className=" p-[0] ">
            <div
              style={{
                width: "100%",
                marginLeft: "5vw",
              }}
            >
              <Container className="m-0 flex fex-row">
                <Navbar.Brand href="/">Navbar</Navbar.Brand>
                <Nav className="me-auto">
                  <Nav.Link
                    href="/employees"
                    style={
                      path === "/employees"
                        ? { color: "grey" }
                        : { color: "white" }
                    }
                  >
                    employees
                  </Nav.Link>
                  <Nav.Link
                    href="/areas"
                    style={
                      path === "/areas" ? { color: "grey" } : { color: "white" }
                    }
                  >
                    areas
                  </Nav.Link>
                  <Nav.Link
                    href="/departments"
                    style={
                      path === "/departments"
                        ? { color: "grey" }
                        : { color: "white" }
                    }
                  >
                    departments
                  </Nav.Link>
                  <Nav.Link
                    href="/transactions"
                    style={
                      path === "/transactions"
                        ? { color: "grey" }
                        : { color: "white" }
                    }
                  >
                    attendance
                  </Nav.Link>
                </Nav>
              </Container>
            </div>
          </Navbar>
        )}
        {children}
      </body>
    </html>
  );
}
